### ISSUE TITLE
Consuming glimmer components from a separate npm package: possible/desirable and how?

### ISSUE THREAD

**Issue by winding-lines** [glimmerjs/glimmer-application-pipeline#112]
I have an npm package containing some glimmer components and I am trying to figure out the proper way (or any way) to consume from a main glimmer application. I see three options:

1. this is not possible or desirable
2. compile hbs on the library side
3. deliver  hbs to the the application

The first question is if it is supported/desirable to package hbs files in a separate npm package. If not what is the recommendation?

If going with library side compilation one possible approach is:

1. use the glimmer compiler to generate js files from hbs
2. have a main file (typescript file?) to import above templates
3. use "main" and "type" properties in package.json to point to the generated files from typescript

If delivering hbs files is preferred then it's unclear  how to specify that in the library's package.json and then how to consume from the client side.

Many thanks for any pointers :)

**Comment by winding-lines** [comment]
Many thanks for the info.

**Comment by rwjblue** [comment]
Also, you can work around this (to see what other issues may present themselves) by re-xporting the components/templates from the consuming app.  Clearly, this is much less useful, but it is a way to continue forward with testing other areas...
