### ISSUE TITLE
Safari 10 compatibility?

### ISSUE THREAD

**Issue by mixonic** [glimmerjs/glimmer-application-pipeline#123]
Refs: https://github.com/201-created/bodega-glimmer/pull/5

Should `uglify` be passed the `mangle: { safari10: true }` option by default?

**Comment by bantic** [comment]
There's a little more detail about this in this glimmer-blueprint issue: https://github.com/glimmerjs/glimmer-blueprint/issues/58

**Comment by rwjblue** [comment]
Yes, we should enable this option by default but we might want to consider adding this to the defaults of ember-cli-uglify until safari10 ages out...

**Comment by acorncom** [comment]
Looks like the fix for this has been merged in `ember-cli-uglify` (https://github.com/ember-cli/ember-cli-uglify/pull/26), can we close this?

**Comment by rwjblue** [comment]
Thanks for the write up @bantic, and thanks for the reminder @acorncom!
