### ISSUE TITLE
Support for Glimmer AST Plugins

### ISSUE THREAD

**Issue by amiller-gh** [glimmerjs/glimmer-application-pipeline#141]
## Expectiation

I can easily supply custom Glimmer AST plugins either in `ember-cli-build.js`, or via an addon.

## Behavior

The invocation site for [`GlimmerJSONCompiler`](https://github.com/glimmerjs/glimmer-application-pipeline/blob/master/lib/broccoli/glimmer-app.ts#L237) has no mechanism to pass Glimmer AST plugins provided in `ember-cli-build.js` to the underlying [`ember-build-utils`](https://github.com/ember-cli/ember-build-utilities/blob/master/lib/compilers/glimmer/index.js) `GlimmerTemplatePrecompiler`, despite plugins being supported by the `ember-build-utils`.

It would be helpful if addons could also provide plugins programmatically! This would probably require more architecting than just passing in plugins from `ember-cli-build.js`.

Related: https://github.com/glimmerjs/glimmer-application-pipeline/issues/139. `glimmer-app` currently does nothing with registered template preprocessors. This makes it that much more difficult to work around the lack of Glimmer plugin support.

**Comment by amiller-gh** [comment]
Please let me know if I've missed any features that already enable this use case 🙂

**Comment by rwjblue** [comment]
Ya, we can leverage the registry (like is done in ember-cli-htmlbars) to allow addons to register their custom AST plugins, then pass them forward to `GlimmerJSONCompiler`...

**Comment by amiller-gh** [comment]
Awesome. Happy to help add a `glimmer-ast-plugin` registry type to the project.

Also, wow `ember-cli-htmlbars` is... "creative" I believe is the polite word 😅If I'm reading it right though, it looks like it should do exactly what this issue is requesting for Glimmer, but in an Ember project.

Ember addons hoping to provide ast plugins for both an Ember and Glimmer project would register both a `glimmer-ast-plugin` *and* an `htmlbars-ast-plugin`, correct?

**Comment by rwjblue** [comment]
Exactly! Also, the `htmlbars-ast-plugins` are expected to be the older style (e.g. a `class { transform() {} }`) now that Ember supports the newer style we should add that to ember-cli-htmlbars too...

**Comment by rwjblue** [comment]
> Also, wow ember-cli-htmlbars is... "creative" I believe is the polite word

confirm 😉

**Comment by amiller-gh** [comment]
Looks like we'll need a 3.2.0 release of `ember-cli-preprocessor-registry` that includes [your updates to `registry.add`](https://github.com/ember-cli/ember-cli-preprocessor-registry/commit/22379e12919520a86101f0f8ef314b7de43e4352#diff-168726dbe96b3ce427e7fedce31bb0bcL60) so we can actually register the new `ASTPluginBuilder` type. I have it working locally with `ember-cli-preprocessor-registry@master` 👍

**Comment by amiller-gh** [comment]
Also of note: 

[GlimmerBundleCompiler](https://github.com/glimmerjs/glimmer-application-pipeline/blob/master/lib/broccoli/glimmer-app.ts#L254) from `@glimmer/app-compiler` needs to accept an array of `ASTPluginBuilder`s in its [options hash](https://github.com/glimmerjs/glimmer.js/blob/master/packages/%40glimmer/app-compiler/src/bundle-compiler.ts#L18), like how `GlimmerTemplatePrecompiler` from `ember-build-utilities` [does](https://github.com/ember-cli/ember-build-utilities/blob/master/lib/compilers/glimmer/index.js#L18).

**Comment by amiller-gh** [comment]
Closed with #145
