### ISSUE TITLE
Unable to import modules from npm

### ISSUE THREAD

**Issue by topaxi** [glimmerjs/glimmer-application-pipeline#75]
I'm not sure how to import things from `npm`.

We need a way to import things, be it in a documented way using broccoli or using `app.import` like in ember.

Personally I'd prefer something like `import { Observable } from 'rxjs/Observable'` to just work.

**Comment by rwjblue** [comment]
Yes, some imports do work (roll up resolves packages that are formatted correctly), but not all. 

There are some changes that we need to add to the rollup config to be able to find others (e.g. CJS packages)

**Comment by rwjblue** [comment]
Enabled by #78, see PR description for details there.
