### ISSUE TITLE
Using ^0.6.0-beta.2 throws error: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by monsteronfire** [glimmerjs/glimmer-application-pipeline#83]
Hello :)

The first app I generated with the `--web-component` flag was using `@glimmer/application-pipeline": "^0.5.2"`, and the use of `async` didn't cause any problems at all.

But I realised that the app I generated today (also using the `--web-component` flag) uses `@glimmer/application-pipeline": "^0.6.0-beta.2"`, and `async` no longer works. It throws the following error:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

I'm not sure if this is the right place to file this issue, but as far as I can tell, the only change was the version of `@glimmer/application-pipeline`.

**Comment by rwjblue** [comment]
We changed things around a bit and now (as of 0.6.x) we emit ES5 code even for web component builds. This means async / await is being transpiled to use regenerator runtime. 

Unfortunately, at this time, there is no simple way of adding back the babel polyfills (or just regenerator runtime). I will try to get this fixed today.

**Comment by monsteronfire** [comment]
Alright. I'll use `^0.5.2` to continue tinkering. :)

Thanks for the quick reply, @rwjblue. I'm enjoying exploring glimmer so far. The team's doing a great job! 💯

**Comment by remzr7** [comment]
@rwjblue any updates?

**Comment by locks** [comment]
Instructions now at https://github.com/glimmerjs/glimmer-application-pipeline#enabling-use-of-async-await-in-components.
